/********************************************************************
* eventData_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error eventData_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableeventData_dict();
extern void G__cpp_setup_inheritanceeventData_dict();
extern void G__cpp_setup_typetableeventData_dict();
extern void G__cpp_setup_memvareventData_dict();
extern void G__cpp_setup_globaleventData_dict();
extern void G__cpp_setup_memfunceventData_dict();
extern void G__cpp_setup_funceventData_dict();
extern void G__set_cpp_environmenteventData_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "eventData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__eventData_dictLN_TClass;
extern G__linked_taginfo G__eventData_dictLN_TBuffer;
extern G__linked_taginfo G__eventData_dictLN_TMemberInspector;
extern G__linked_taginfo G__eventData_dictLN_TObject;
extern G__linked_taginfo G__eventData_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__eventData_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventData_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__eventData_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventData_dictLN_eventData;

/* STUB derived class for protected member access */
