/********************************************************************
* ExpEventDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ExpEventDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableExpEventDictionary();
extern void G__cpp_setup_inheritanceExpEventDictionary();
extern void G__cpp_setup_typetableExpEventDictionary();
extern void G__cpp_setup_memvarExpEventDictionary();
extern void G__cpp_setup_globalExpEventDictionary();
extern void G__cpp_setup_memfuncExpEventDictionary();
extern void G__cpp_setup_funcExpEventDictionary();
extern void G__set_cpp_environmentExpEventDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/afs/crc.nd.edu/group/nsl/nuc/users/sstrauss/iceball_dec2014/Code/Iceball-Coin-Timing/include/eventData.h"
#include "/afs/crc.nd.edu/group/nsl/nuc/users/sstrauss/iceball_dec2014/Code/Iceball-Coin-Timing/include/eventScaler.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ExpEventDictionaryLN_TClass;
extern G__linked_taginfo G__ExpEventDictionaryLN_TBuffer;
extern G__linked_taginfo G__ExpEventDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__ExpEventDictionaryLN_TObject;
extern G__linked_taginfo G__ExpEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ExpEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExpEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ExpEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExpEventDictionaryLN_eventData;
extern G__linked_taginfo G__ExpEventDictionaryLN_eventScaler;

/* STUB derived class for protected member access */
